In [2]:
import numpy as np
from numpy import linalg as LA
import scipy.linalg

In [5]:
# GAUSOVE ELIMINACIJE - s pivotiranjem 
import numpy as np
from numpy import linalg as LA
import scipy.linalg
def gausove_eliminacije(A,b):
    n = len(A)

    # Forward elimination
    for pivot_row in range(n-1):
        for row in range(pivot_row+1, n):
            factor = A[row][pivot_row] / A[pivot_row][pivot_row]
            for col in range(pivot_row, n):
                A[row][col] -= factor * A[pivot_row][col]
            b[row] -= factor * b[pivot_row]
    # Back substitution
    x = [0] * n
    for i in range(n-1, -1, -1):
        x[i] = b[i] / A[i][i]
        for j in range(i+1, n):
            x[i] = x[i] - A[i][j] * x[j] / A[i][i]

    return x
A=np.array([[0.1, 1, -1],
           [-3, 0, 2],
           [-2, 1, 1]])
b=np.array([8, -11, -3])
rjesenje = gausove_eliminacije(A,b)
print("rjesenje:", rjesenje)

rjesenje: [0.3333333333333215, 2.96666666666665, -5.000000000000018]


In [6]:
print(np.matmul(A,rjesenje))

[  8. 229.  -3.]


In [13]:
# GAUSOVE ELIMINACIJE - parcijano pivotiranje 
#traži se najveći element po apsolutnoj vrijednosti u stupcu pivotiranja i zamjenjuje ga se s trenutnim pivotom 
def gauss_elimination_pivot(A, b):
    n = len(b)

    # Augmented matrix
    M = np.concatenate((A, b.reshape(n, 1)), axis=1)
    # Forward elimination
    for i in range(n):
        # Partial pivoting
        max_row = i
        for k in range(i+1, n):
            if abs(M[k][i]) > abs(M[max_row][i]):
                max_row = k
        M[[i, max_row]] = M[[max_row, i]]  # Swap rows

        # Elimination step
        for j in range(i+1, n):
            ratio = M[j][i] / M[i][i]
            M[j] -= ratio * M[i]

    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = M[i][n] / M[i][i]
        for k in range(i-1, -1, -1):
            M[k][n] -= M[k][i] * x[i]

    return x

# Example usage:
A=np.array([[0.1, 1, -1],
           [-3, 0, 2],
           [-2, 1, 1]])
b = np.array([8, -11, -3])

x = gauss_elimination_pivot(A, b)
print("Solution:", x)

Solution: [-0.   2.5 -5.5]


In [14]:
print(np.matmul(M,x))

[  8. -11.  -3.]


In [21]:
# dopušta li matrica faktorizaciju ? 
# Matrica dopušta LU faktorizaciju ako i samo ako sve njene glavne podmatrice imaju ne-nula determinante.
import numpy as np

# Definicija matrice A
A = np.array([[0, 0, 2, 2],
              [2, 2, 4, 2],
              [1, 2, 1, -1],
              [-1, 1, -1, 5]])

# Provjera determinanti glavnih podmatrica
regularna = True
n = A.shape[0]  # Veličina matrice A

for i in range(1, n+1):
    # Izračunavanje determinante glavne podmatrice
    det_A_i = np.linalg.det(A[:i, :i])
    
    # Provjera jesu li sve determinante različite od nule
    if det_A_i == 0:
        regularna = False
        break

# Ispis rezultata
if regularna:
    print("Matrica A dopušta LU faktorizaciju.")
else:
    print("Matrica A ne dopušta LU faktorizaciju.")

Matrica A ne dopušta LU faktorizaciju.


In [39]:
import numpy as np
import scipy.linalg as la

# Definicija matrice A
A = np.array([[0, 0, 2, 2],
              [2, 2, 4, 2],
              [1, 2, 1, -1],
              [-1, 1, -1, 5]])

# Izračunavanje PLU faktorizacije s parcijalnim pivotiranjem
P, LU = la.lu(A, permute_l=True)

# Razdvajanje matrice LU na L i U
L = np.tril(LU, k=-1) + np.eye(A.shape[0])
U = np.triu(LU)

# Ispis rezultata
print("Matrica P (matrica permutacija):")
print(P)
print("\nMatrica L (donjetrokutasta matrica):")
print(L)
print("\nMatrica U (gornjetrokutasta matrica):")
print(U)



Matrica P (matrica permutacija):
[[ 0.    0.    1.    0.  ]
 [ 1.    0.    0.    0.  ]
 [ 0.5   0.5  -0.75  1.  ]
 [-0.5   1.    0.    0.  ]]

Matrica L (donjetrokutasta matrica):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matrica U (gornjetrokutasta matrica):
[[ 2.   2.   4.   2. ]
 [ 0.   2.   1.   6. ]
 [ 0.   0.   2.   2. ]
 [ 0.   0.   0.  -3.5]]


In [40]:
#Koristeći dobivenu PLU faktorizaciju od 𝐴, nađite 𝑥 ∈ ℝ4
#koji je rješenje sustava 𝐴𝑥 = 𝑏, ako je 𝑏 = [2 8 6 −4]𝑇
import numpy as np

def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i, i]
    return y

def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

# Matrice P, L, U i vektor b
P = np.array([[ 0. ,  0. ,  1. ,  0. ],
              [ 1. ,  0. ,  0. ,  0. ],
              [ 0.5,  0.5, -0.75,  1. ],
              [-0.5,  1. ,  0. ,  0. ]])

L = np.array([[1., 0., 0., 0.],
              [0., 1., 0., 0.],
              [0., 0., 1., 0.],
              [0., 0., 0., 1.]])

U = np.array([[ 2. ,  2. ,  4. ,  2. ],
              [ 0. ,  2. ,  1. ,  6. ],
              [ 0. ,  0. ,  2. ,  2. ],
              [ 0. ,  0. ,  0. , -3.5]])

b = np.array([2, 8, 6, -4])

# Rješavanje sustava Ax = b
y = forward_substitution(L, np.dot(P, b))
x = backward_substitution(U, y)

# Ispis rješenja
print("Rješenje sustava Ax = b:")
print(x)


Rješenje sustava Ax = b:
[-2.375  6.875  0.25  -2.   ]


In [41]:
#ako je A pozitivno definitna matrica dimenzija n×n, faktorizacija Choleskyja daje matricu L dimenzija n×n takvu da 
# A = LL^T

import numpy as np

# Definiranje pozitivno definitne matrice A
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])

# Izračunavanje faktorizacije Choleskog
L = np.linalg.cholesky(A)

print("Faktorizacija Choleskog matrice A:")
print(L)

Faktorizacija Choleskog matrice A:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [42]:
#zadatak 3 
# argument p koristimo kako bismo definirali koju normu koristimo -> 1 za l1 i ∞ za l∞
# pomoću funkcije cond možemo izračunati uvjetovanost matrice A s različitim normama
import numpy as np
import scipy.linalg
A = np.array([[5, 3, 6],
              [6, 2, 3],
              [4, 2, 5]], dtype=float)
uvjetovanost_jedan = np.linalg.cond(A, p=1)
uvjetovanost_beskonacno = np.linalg.cond(A, p=np.inf)

print("Uvjetovanost ‖⋅‖1:", uvjetovanost_jedan)
print("Uvjetovanost ‖⋅‖∞:", uvjetovanost_beskonacno)

Uvjetovanost ‖⋅‖1: 48.0
Uvjetovanost ‖⋅‖∞: 56.0
