In [1]:
#[Handouts] zadatak 9. 
# dolazi do manje pogreške pri zapisu nekih brojeva u računalo te zbog toga vrijednost nije istinita 
# 0.1 ima periodičan zapis u binarnom sustavu te kad se koristi u računanju dolazi do manjih pogrešaka
# takve pogreške su dovoljne da navedena jednakost ne bude istinita ( rezultat je približno 0.3 )

In [13]:
#[Handouts] zadatak 15. 
import numpy as np
N = 10000
A = np.arange( 1, N + 1 ) 
sum(1/A)

9.787606036044348

In [12]:
#[Handouts] zadatak 15.
B = np.arange(1, N + 1)
B = B[::-1]
sum(1/B)

9.787606036044386

In [14]:
#[Handouts] zadatak 15.
# rezultati se razlikuju, točniji je drugi primjer gdje se zbrajaju najprije manji brojevi i tada dolazi do veće pogreške 
# potpuno jednake rezultate moguće je dobiti uz korištenje dtype = float

In [17]:
# zadatak 1 a)
import numpy as np
import scipy.linalg

A = np.array([[1, -1, 0, 1],
              [-1, 3, -1, 2],
              [2, -4, 0, 6],
              [1, 3, -1, 3]], dtype=float)

b = np.array([1, -1, 0, 1])
if np.linalg.det(A) == 0:
    print("Matrica ne dopušta LU faktorizaciju. Nije moguće riješiti ovakav sustav.")
else:
    P, L, U = scipy.linalg.lu(A)
    y = np.linalg.solve(L, b)
    x = np.linalg.solve(U, y)

    print("Rješenje sustava Ax = b je:", x)
# koristi se scipy.linalg za dobivanje LU faktorizacije

Rješenje sustava Ax = b je: [ 0.16666667 -2.16666667 -9.33333333 -1.33333333]


In [18]:
# zadatak 1 b)
import numpy as np
import scipy.linalg

A = np.array([[1, -1, 0, 1],
              [-1, 3, -1, 2],
              [2, -4, 0, 6],
              [1, 3, -1, 3]], dtype=float)
P, L, U = scipy.linalg.lu(A)

print("LU faktorizacija matrice A:")
print("P matrica:")
print(P)
print("\nL matrica:")
print(L)
print("\nU matrica:")
print(U)


LU faktorizacija matrice A:
P matrica:
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

L matrica:
[[ 1.    0.    0.    0.  ]
 [ 0.5   1.    0.    0.  ]
 [-0.5   0.2   1.    0.  ]
 [ 0.5   0.2  -0.25  1.  ]]

U matrica:
[[ 2.   -4.    0.    6.  ]
 [ 0.    5.   -1.    0.  ]
 [ 0.    0.   -0.8   5.  ]
 [ 0.    0.    0.   -0.75]]


In [24]:
# zadatak 1 c) 
import numpy as np
import scipy.linalg
A = np.array([[1, -1, 0, 1],
              [-1, 3, -1, 2],
              [2, -4, 0, 6],
              [1, 3, -1, 3]], dtype=float)
b = np.array([1, -1, 0, 1])

if np.linalg.det(A) == 0:
    print("Nije moguće riješiti sustav.")
else:
    P, L, U = scipy.linalg.lu(A)
    b = b.reshape(-1, 1)
    y = np.linalg.solve(L, np.dot(P, b))
    x = np.linalg.solve(U, y)

    print("Rješenje sustava Ax = b je:", x.flatten())



Rješenje sustava Ax = b je: [-1.16666667  1.16666667  6.33333333  1.33333333]


In [25]:
# zadatak 2 a)
# najprije provjeravamo jesu li dijagonalni elementi matrice L jednaki 0 - ako jesu, nije moguće izvršiti faktorizaciju
import numpy as np
import scipy.linalg
A = np.array([[0, 0, 2, 2],
              [2, 2, 4, 2],
              [1, 2, 1, -1],
              [-1, 1, -1, 5]], dtype=float)

if np.linalg.det(A) == 0:
    print("Ne dopušta LU faktorizaciju.")
else:
    try:
        P, L, U = scipy.linalg.lu(A)
        print("Matrica A dopušta LU faktorizaciju.")
    except scipy.linalg.LinAlgError:
        print("Matrica A ne dopušta LU faktorizaciju.")


Matrica A dopušta LU faktorizaciju.


In [38]:
# zadatak 2 b) i c)
# kako bismo omogućili parcijalno pivotiranje, postavljamo parametar permute_l na "true"
# ostatak koda je izračun P, L i U matrica
# zbog korištenja parametra za parcijalno pivotiranje, možemo dobiti jedino LU te je zbog toga potrebno još razdvojiti gornje trokutastu i donje trokutastu matricu
# koristimo funkcije tril i triu za razdvajanje L i U 
# np.eye kreira matricu jedinicama na dijagonali i nulama izvan dijagonale ( matrica je n x n ) 
import numpy as np
import scipy.linalg

A = np.array([[0, 0, 2, 2],
              [2, 2, 4, 2],
              [1, 2, 1, -1],
              [-1, 1, -1, 5]], dtype=float)
b = np.array([2, 8, 6, -4])
P, LU = scipy.linalg.lu(A, permute_l=True)

n = len(A)
L = np.tril(LU, k=-1) + np.eye(n)
U = np.triu(LU)

print("Permutacijska matrica P:")
print(P)
print("\nDonja trokutasta matrica L:")
print(L)
print("\nGornja trokutasta matrica U:")
print(U)

# c)
# funkcija reshape koristi se za transponiranje matrice b 
b = b.reshape(-1, 1)
y = np.linalg.solve(L, np.dot(P, b))
x = np.linalg.solve(U, y)

print("\nRješenje sustava Ax = b je:", x.flatten())


Permutacijska matrica P:
[[ 0.    0.    1.    0.  ]
 [ 1.    0.    0.    0.  ]
 [ 0.5   0.5  -0.75  1.  ]
 [-0.5   1.    0.    0.  ]]

Donja trokutasta matrica L:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Gornja trokutasta matrica U:
[[ 2.   2.   4.   2. ]
 [ 0.   2.   1.   6. ]
 [ 0.   0.   2.   2. ]
 [ 0.   0.   0.  -3.5]]

Rješenje sustava Ax = b je: [-2.375  6.875  0.25  -2.   ]


In [46]:
#zadatak 3 
# argument p koristimo kako bismo definirali koju normu koristimo -> 1 za l1 i ∞ za l∞
# pomoću funkcije cond možemo izračunati uvjetovanost matrice A s različitim normama
import numpy as np
import scipy.linalg
A = np.array([[5, 3, 6],
              [6, 2, 3],
              [4, 2, 5]], dtype=float)
uvjetovanost_jedan = np.linalg.cond(A, p=1)
uvjetovanost_beskonacno = np.linalg.cond(A, p=np.inf)

print("Uvjetovanost ‖⋅‖1:", uvjetovanost_jedan)
print("Uvjetovanost ‖⋅‖∞:", uvjetovanost_beskonacno)


Uvjetovanost ‖⋅‖1: 48.0
Uvjetovanost ‖⋅‖∞: 56.0


In [57]:
# zadatak 4 - notebook datoteka s Moodle-a
# pomoću ovog primjera s algoritmom Gaussovih eleminacija ne možemo dobiti rješenje jer je matrica blizu singularnosti 
# potrebno je koristiti djelomično pivotiranje kako bismo dobili rezultate 
import numpy as np

def gauss_elimination(A, b):
    n = len(A)
    for pivot_row in range(n-1):
        for row in range(pivot_row+1, n):
            factor = A[row][pivot_row] / A[pivot_row][pivot_row]
            for col in range(pivot_row, n):
                A[row][col] -= factor * A[pivot_row][col]
            b[row] -= factor * b[pivot_row]

    x = [0] * n
    for i in range(n-1, -1, -1):
        x[i] = b[i] / A[i][i]
        for j in range(i+1, n):
            x[i] = x[i] - A[i][j] * x[j] / A[i][i]

    return x

A = np.array([[1e-17, 1],
              [1, 1]])
b = np.array([1, 2])

rjesenje = gauss_elimination(A, b)
print("rješenje:", rjesenje)

OverflowError: Python int too large to convert to C long

In [58]:
# zadatak 4 - 1. način 
# djelomično pivotiranje 
import numpy as np
import scipy.linalg

A = np.array([[1e-17, 1], [1, 1]])
b = np.array([1, 2])

P, L, U = scipy.linalg.lu(A)

y = np.linalg.solve(L, np.dot(P, b))
x = np.linalg.solve(U, y)

print("Rješenje sustava Ax = b je:", x)


Rješenje sustava Ax = b je: [1. 1.]


In [59]:
# zadatak 4 - 2. način ( primjer iz notebook datoteke s Moodle-a )
# djelomično pivotiranje 
# dobivamo ista rješenja kao na prvi način, a u usporedbi s primjerom bez pivotiranja - daje rezultat 

def gauss_elimination_pivot(A, b):
    n = len(b)

    # Augmented matrix
    M = np.concatenate((A, b.reshape(n, 1)), axis=1)

    # Forward elimination
    for i in range(n):
        # Partial pivoting
        max_row = i
        for k in range(i+1, n):
            if abs(M[k][i]) > abs(M[max_row][i]):
                max_row = k
        M[[i, max_row]] = M[[max_row, i]]  # Swap rows

        # Elimination step
        for j in range(i+1, n):
            ratio = M[j][i] / M[i][i]
            M[j] -= ratio * M[i]

    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = M[i][n] / M[i][i]
        for k in range(i-1, -1, -1):
            M[k][n] -= M[k][i] * x[i]

    return x

# Example usage:
A = np.array([[1e-17, 1], [1, 1]])
b = np.array([1, 2])

x = gauss_elimination_pivot(A, b)
print("Rjesenje:", x)

Rjesenje: [1. 1.]


In [61]:
# zadatak 4 - uz pomoć gotove funkcije numpy.linalg.solve 
# dobivamo ista rješenja kao u prethodna dva primjera
import numpy as np

A = np.array([[1e-17, 1], [1, 1]])
b = np.array([1, 2])

x_numpy = np.linalg.solve(A, b)

print("Rješenje sustava korištenjem gotove funkcije :", x_numpy)


Rješenje sustava korištenjem gotove funkcije : [1. 1.]
