In [1]:
import numpy as np

# Postavljanje veličine matrice
n = 5

# Inicijalizacija matrice s nulama
A = np.zeros((n, n))

# Postavljanje jedinica na dijagonali
np.fill_diagonal(A, 1)

# Postavljanje trojki iznad dijagonale
for i in range(n):
    for j in range (n):
        if(i<j):
            A[i, j] = 3
        if(i>j):
            A[i,j] = 4

# Postavljanje dvojki ispod dijagonale
#for i in range(1, n):
   # A[i, i-1] = 2

print(A)

[[1. 3. 3. 3. 3.]
 [4. 1. 3. 3. 3.]
 [4. 4. 1. 3. 3.]
 [4. 4. 4. 1. 3.]
 [4. 4. 4. 4. 1.]]


In [5]:
import numpy as np

# Generiranje matrice 50x50 s jedinicama na dijagonali, trojkama iznad dijagonale i dvojkama ispod dijagonale
n = 50
A = np.zeros((n, n))
np.fill_diagonal(A, 1)
for i in range(n-1):
    A[i, i+1] = 3
for i in range(1, n):
    A[i, i-1] = 2

# Generiranje druge matrice 50x50 s elementima 2
B = np.full((n, n), 2)

# Matrično množenje
C = np.matmul(A, B)
# množenje matrica skalarom 
D  = C * 2 

print(C)
print(D)

[[ 8.  8.  8. ...  8.  8.  8.]
 [12. 12. 12. ... 12. 12. 12.]
 [12. 12. 12. ... 12. 12. 12.]
 ...
 [12. 12. 12. ... 12. 12. 12.]
 [12. 12. 12. ... 12. 12. 12.]
 [ 6.  6.  6. ...  6.  6.  6.]]
[[16. 16. 16. ... 16. 16. 16.]
 [24. 24. 24. ... 24. 24. 24.]
 [24. 24. 24. ... 24. 24. 24.]
 ...
 [24. 24. 24. ... 24. 24. 24.]
 [24. 24. 24. ... 24. 24. 24.]
 [12. 12. 12. ... 12. 12. 12.]]


In [6]:
import numpy as np

# Primjer matrice
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Transponiranje matrice pomocu atributa T
A_transpose = A.T

# Transponiranje matrice pomocu funkcije np.transpose()
A_transpose_alt = np.transpose(A)

print("Originalna matrica A:")
print(A)
print("\nTransponirana matrica A:")
print(A_transpose)
print("\nTransponirana matrica A (alternativni način):")
print(A_transpose_alt)

Originalna matrica A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transponirana matrica A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transponirana matrica A (alternativni način):
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
import struct

# Broj koji želimo predstaviti
number = 3.75

# Konvertiramo broj u 32-bitni float
binary_representation = struct.pack('>f', number)

# Konvertiramo 32-bitni float u binarni zapis
binary_string = ''.join(f'{byte:08b}' for byte in binary_representation)

# Ispis binarnog zapisa
print("Binarni zapis broja 3.75:", binary_string)


Binarni zapis broja 3.75: 01000000011100000000000000000000


In [13]:
# Binarni zapis znaka, eksponenta i mantise
binary_sign = '1'
binary_exponent = '10000000'
binary_mantissa = '11000000000000000000000'

# Pretvorba binarnog znaka u decimalni broj
sign = int(binary_sign, 2)

# Pretvorba binarnog eksponenta u decimalni broj
exponent = int(binary_exponent, 2)

# Pretvorba binarne mantise u decimalni broj
mantissa = int(binary_mantissa, 2)

# Pretvaranje u float
result = (-1) ** sign * (1 + mantissa / 2**23) * 2**(exponent - 127)

# Ispis rezultata
print("Rezultat:", result)


Rezultat: -3.5
